server.port=8080
spring.application.name=${SPRING_APP_NAME:secu}
spring.security.user.name=${USERNAME:hadeel}
spring.security.user.password=${PASSWORD:123}

spring.output.ansi.enabled=always

logging.pattern.console=${LOGPATTERN_CONCOLE:%green(%d{HH:mm:ss.SSS}) %highlight(%-5level) %cyan(%logger{20}) %yellow([%thread]) - %msg%n}
logging.level.root=INFO
logging.level.com.sp=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
